sudo: true
language: cpp

compiler:
  - gcc

before_install:
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo pip install codecov
  - sudo apt-get update -qq

install: 
  - sudo apt-get install -qq g++-5
  - sudo apt-get install -qq gcov-5

addons:
  apt:
    sources:
    - boost-latest
    - ubuntu-toolchain-r-test
    packages:
    - gcc-4.8
    - g++-4.8
    - libboost1.55-all-dev

before_script:
  - ./download_other_githubs.sh

script: 
  - ./build_console_test.sh
  - ./PreDickAdvocaTorConsoleTest
  - ./get_code_cov.sh
  - codecov
  - ./clean.sh
  - ./build_console.sh
  - ./build_desktop.sh